# Generated by Django 3.2.8 on 2021-10-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('Good', 'Good'), ('Defective but working', 'Defective but working'), ('None functional', 'None functional'), ('Damaged', 'Damaged')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='location',
            field=models.CharField(choices=[('Basement', 'Basement'), ('Mekdes (Oltor)', 'Mekdes (Oltor)'), ('Clergy room 4', 'Clergy room 4'), ('Clergy living room', 'Clergy living room'), ('Congregation area (Northex)', 'Congregation area (Northex)'), ('Clergy room 3', 'Clergy room 3'), ('Clergy kitchen', 'Clergy kitchen'), ('Clergy room 2', 'Clergy room 2'), ('Clergy room 1', 'Clergy room 1'), ('Baptism room', 'Baptism room'), ('Church upstairs', 'Church upstairs'), ('Rest room', 'Rest room'), ('Class room 16', 'Class room 16'), ('Mezemiran room 2', 'Mezemiran room 2'), ('Mezemiran room 1', 'Mezemiran room 1'), ('Shop', 'Shop'), ('Board meeting room', 'Board meeting room'), ('Office 1', 'Office 1'), ('Office 2', 'Office 2'), ('Office 3', 'Office 3'), ('office reseption', 'office reseption'), ('Library', 'Library'), ('Class room 1', 'Class room 1'), ('Class room  2', 'Class room  2'), ('Class room 3', 'Class room 3'), ('Class room 4', 'Class room 4'), ('Class room 5', 'Class room 5'), ('Amanuel room', 'Amanuel room'), ('Kitchen', 'Kitchen'), ('Restroom 1', 'Restroom 1'), ('Restroom 2', 'Restroom 2'), ('Class room 6', 'Class room 6'), ('Prep room 2', 'Prep room 2'), ('Audio room', 'Audio room'), ('Storage', 'Storage'), ('Hall', 'Hall'), ('Hall reseption area', 'Hall reseption area'), ('Stage 1', 'Stage 1'), ('Prep room 1', 'Prep room 1'), ('Storage 2', 'Storage 2')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='source_received',
            field=models.CharField(choices=[('Donation', 'Donation'), ('Purchased', 'Purchased'), ('Built on site', 'Built on site')], max_length=50, null=True),
        ),
    ]
