# Generated by Django 3.2.8 on 2023-11-11 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20211022_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='count',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='location',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='source_received',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='tag',
        ),
    ]
