# Generated by Django 3.2.8 on 2021-10-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
